# Generated by Django 2.2.7 on 2019-12-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('DO', 'DOMINICAN'), ('USA', 'AMERICAN'), ('VEN', 'VENEZUELAN')], default='DO', max_length=3)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
