# Generated by Django 2.2.7 on 2019-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('identification', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
