# Generated by Django 2.2.7 on 2019-12-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25)),
                ('surname', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('DOMINICAN', 'DOMINICAN'), ('AMERICAN', 'AMERICAN'), ('VENEZUELAN', 'VENEZUELAN')], default='DOMINICAN', max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('SALARIO', 'SALARIO'), ('POR HORA', 'POR HORA')], default='SALARIO', max_length=8)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('feriado_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='human_resources.Employee')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Nomina')),
            ],
        ),
    ]
