# Generated by Django 2.2.7 on 2019-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='employees',
            field=models.ManyToManyField(to='human_resources.Employee'),
        ),
    ]
