# Generated by Django 2.2.7 on 2019-12-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_auto_20191204_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='Haydee', max_length=25),
            preserve_default=False,
        ),
    ]
