# Generated by Django 2.2.7 on 2019-12-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_auto_20191204_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(choices=[('SALARIO', 'SALARIO'), ('POR HORA', 'POR HORA')], default='SALARIO', max_length=8),
        ),
    ]
