# Generated by Django 2.2.7 on 2019-12-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_comprobante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
