# Generated by Django 2.2.7 on 2019-12-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_comprobantesalario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='human_resources.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='ComprobanteSalario',
        ),
    ]
