# Generated by Django 2.2.7 on 2019-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_auto_20191207_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=88, max_digits=8),
        ),
    ]
