# Generated by Django 2.2.7 on 2019-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_comprobante_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='normal_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
