# Generated by Django 2.2.7 on 2019-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_auto_20191207_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='feriado_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('DOMINICAN', 'DOMINICAN'), ('AMERICAN', 'AMERICAN'), ('VENEZUELAN', 'VENEZUELAN')], default='DOMINICAN', max_length=10),
        ),
    ]
