# Generated by Django 2.2.7 on 2019-12-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_auto_20191209_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
            ],
        ),
    ]
